### PR TITLE
Spell check GitHub action

### PR DESCRIPTION
**Pull request by WalterSmuts**
This *shouldn't* get in the way of development too much. It's [designed](https://github.com/crate-ci/typos/blob/master/docs/design.md) to work with code and have a low false-positive count. Feel free to drop the `Add github spell check workflow` commit if you recon it'll be more hassle than  worth.

### CODE REVIEW

**Comment by dabrahams** [comment]
This is awesome.  My only question: what's the procedure for silencing a false positive?

**Comment by WalterSmuts** [comment]
> My only question: what's the procedure for silencing a false positive?

Add it to the `[default.extend-words]` in the `.typos.toml` file. There's already two defined:
```
inout = "inout" # Mutable projection keyword
olt = "olt" # Abbreviation for "ordered less than"
```

The list is defined as a map of valid corrections. TBH not too sure why it's a correction in this case. Likely related to the tool working off of correction lists and not valid lists. See [the docs on false positives](https://github.com/crate-ci/typos#false-positives) for more info.

**Comment by dabrahams** [comment]
If you could add something to [this text](https://github.com/hylo-lang/hylo/blob/main/CONTRIBUTING.md#contributing-code) describing how contributors can spell-check their code locally, I think we can accept this PR with gratitude!

**Comment by WalterSmuts** [comment]
Think that should suffice :+1:

**Pull request merged**
