### PR TITLE
Change the way to organizing tests

### PR DESCRIPTION
**Pull request by C-BJ**
Fixes: #436
I cannot guarantee that I fully understand the meaning of #436.
 If there is anything I have misunderstood, please mention it.
@kyouko-taiga

### CODE REVIEW

**Comment by kyouko-taiga** [comment]
Sorry for the slow response time. I'm attending a conference this week so I'll take a closer look at your PR over the weekend.

**Comment by C-BJ** [comment]
In case you didn't see it, please check out: https://github.com/val-lang/vscode-val/pull/1 @kyouko-taiga

**Comment by kyouko-taiga** [comment]
The PR gets us closer to what I'd like to implement, but we're not completely there yet. There are some changes we need to make on the tests themselves, not simply move files around. Most significantly, I'd like `CompilerTests/` to contain all (and only) integration tests as Val files that would be processed by a single runner written in Swift.

Do you mind if we put this PR on hold for a little? I think it will be easier to merge it once the LLVM backend lands. Perhaps I could also take it from there, since I have a clear idea of the whole picture.

**Comment by C-BJ** [comment]
ok

**Pull request closed without merging**
